Worked on porting tensorflow to version 1.1. All unit test passes
gheinrich/DIGITS-GAN pull request #1
Opened 2017-05-15 21:18 UTC by ethantang95

majority of the changes are within the tensorflow work or tool files. All the unit tests passes.

Some commits were done with respect to IDE files but they are all removed.

2017-05-15 21:51 UTC, gheinrich reviewed
Thanks @ethantang95 can you remove unnecessary changes please?

2017-05-15 21:51 UTC, gheinrich commented on digits/dataset/images/classification/test_views.py
> +        print("Sending request to: " + url)
can you clean these up please?

2017-05-15 22:02 UTC, ethantang95 commented
done

2017-05-16 06:26 UTC, gheinrich requested changes
Hi @ethantang95 can you remove unnecessary changes, squash your commits and update https://github.com/gheinrich/DIGITS-GAN/blob/master/scripts/travis/install-tensorflow.sh to install the right version of Tensorflow.

2017-05-16 06:26 UTC, gheinrich commented on .gitignore
> +.vscode
files should end with a blank line

2017-05-16 06:26 UTC, gheinrich commented on digits/config/tensorflow.py
> +    print('Failed importing Tensorflow with python executable "%s"\n%s' % (tf_python_exe, err))
doesn't seem necessary

2017-05-16 06:26 UTC, gheinrich commented on digits/dataset/images/classification/views.py
> +            print("going into folder")
please remove *all* print statements

2017-05-16 06:26 UTC, gheinrich commented on digits/job.py
> +logger = logging.getLogger('digits.tools.inference')
doesn't seem necessary

2017-05-16 06:26 UTC, gheinrich commented on digits/model/images/classification/test_views.py
> +        result = cls.model_wait_completion(cls.model_id)
doesn't seem necessary

2017-05-16 06:26 UTC, gheinrich commented on digits/test_views.py
> +                print("Job " + job_id + " took too long to finish")
unnecessary

2017-05-16 06:26 UTC, gheinrich commented on digits/tools/inference.py
> +    trained_task = model.train_task()
unnecessary

2017-05-16 06:26 UTC, gheinrich commented on digits/tools/tensorflow/model.py
> +            grads_transformed = tf.reduce_mean(grads_transformed, 0)
are you sure about that?

2017-05-16 06:26 UTC, gheinrich commented on docs/DevelopmentSetup.md
> +Running the development server allow you to <TBD>
either remove or complete sentence

2017-05-16 16:51 UTC, ethantang95 commented on digits/tools/tensorflow/model.py
> +            grads_transformed = tf.reduce_mean(grads_transformed, 0)
Yeah, the new API swaps the place of them

2017-05-16 18:59 UTC, gheinrich reviewed
can you also squash your commits and fix `./digits-lint` errors?

2017-05-16 18:59 UTC, gheinrich commented on digits/job.py
> +import logging
seems unnecessary

2017-05-16 18:59 UTC, gheinrich commented on digits/model/images/classification/test_views.py
> +        print("task id="+str(self.model_id))
this too

2017-05-16 18:59 UTC, gheinrich commented on digits/model/job.py
> +
this too

2017-05-16 18:59 UTC, gheinrich commented on digits/tools/inference.py
> +
this too

2017-05-16 18:59 UTC, gheinrich commented on digits/tools/inference.py
> +import json
we don't need this

2017-05-16 18:59 UTC, gheinrich commented on digits/tools/tensorflow/model.py
> +            grads_transformed = tf.reduce_mean(grads_transformed, 0)
ah OK thanks can you make sure multi-GPU training still works?

2017-05-16 19:05 UTC, ethantang95 commented on digits/tools/tensorflow/model.py
> +            grads_transformed = tf.reduce_mean(grads_transformed, 0)
I do not have a multi-gpu system, know who I can talk to for one?

2017-05-16 22:49 UTC, ethantang95 commented
all changes done

2017-05-17 19:31 UTC, gheinrich approved these changes

2017-05-17 19:31 UTC, merged